services:
  postgres:
    container_name: vacancy_database
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=tobias
      - POSTGRES_PASSWORD=11591004
      - POSTGRES_DB=vacancy

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - vcm-network
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - vcm-network

volumes:
  prometheus_data:
  grafana_data:

networks:
  vcm-network:
    driver: bridge